

- name: Copy configurtion
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: configure redis
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis service
  ansible.builtin.systemd_service:
    state: started
    name: redis
    enabled: yes