
#curl -s -o /etc/yum.repos.d/mongodb.repo https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo


- name: download and Extract
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

# yum install -y mongodb-org
# systemctl enable mongod
# systemctl start mongod

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed



- name: configure MongoDB
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start mongodb service
  ansible.builtin.systemd_service:
    name: mongod
    state: started
    enabled: yes

- name: download and Extract mongoDB
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load catalogue schema
  community.mongodb.mongodb_shell:
    file: "/tmp/*/catalogue.js"
    idempotent: yes

