#- name: Roboshop setup
#  hosts: frontend
#  become: yes
#  roles:
#    - frontend
#- name: Roboshop setup
#  hosts: mongodb
#  become: yes
#  roles:
#    - mongodb
#- name: Roboshop setup
#  hosts: catalogue
#  become: yes
#  roles:
#    - catalogue


- name: Roboshop setup
  become: yes
  hosts: "{{HOST}}"
  roles:
    - "{{role_name}}"
