- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

    # curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"



- name: download and extract frontend
  ansible.builtin.include_role:
    name: common
    tasks_from: download

# cd /usr/share/nginx/html
- name: clean up remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

# unzip /tmp/frontend.zip
# mv frontend-main/static/* .

- name: download and Extract
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy configurtion
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Enable nginx service
  ansible.builtin.systemd:
    name: nginx


- name: Start nginx service
  ansible.builtin.systemd_service:
    state: started
    name: nginx
    enabled: yes

