# curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Configure Yum Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install catalogue components
  ansible.builtin.yum:
    name:
      - nodejs
    state: installed









# useradd roboshop
- name: Add application user
  ansible.builtin.user:
    name: roboshop
    comment: Add user to roboshop application

    #    $ curl -s -L -o /tmp/catalogue.zip "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"

- name: download and extract catalogue
  ansible.builtin.include_role:
    name: common
    tasks_from: download

#    $ cd /home/roboshop
- name: clean up and remove directory
  ansible.builtin.file:
    path: /home/roboshop
    state: absent

- name: Copy app content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: Install nodejs dependence
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

