  - name: Play level variables
    hosts: all
    vars:
      URL: play.example.com
    tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL = {{URL}}

  # If we declare a varible on play level then all the tasks can access that variable

  - name: Play level variables from a file
    hosts: all
    vars_files:
      - sample.yml
    tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL = {{URL}}

  - name: Task level varibles
    hosts: all
    tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL = {{URL}}
        vars:
          URL: Task.varabiles.com

  - name: inventory varibles
    hosts: all
    tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL = {{URL}}

  - name: fact varibles
    hosts: all
    tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: Ansible_bios_date= {{ansible_bios_date}},IPV4={{ansible_eth0.ipv4.address}}

          #IP address = {{ansible_eth0.ipv4.address}}
